In [1]:
import os
import gc
import cv2
import torch
import numpy as np
from tqdm import tqdm
import matplotlib.pyplot as plt

from ultralytics.models import YOLO
from ultralytics.models.yolo.detect.train import DetectionTrainer
from ultralytics.cfg import cfg2dict, get_cfg
from ultralytics.data.build import build_dataloader, build_yolo_dataset

from utils.tools import (boxes_to_coor, compute_normalized_cross_correlation,
                         delete_min_object_iter, delete_temp_img,
                         save_loss, save_visualize_image)

# Utils

In [2]:
from ultralytics.utils.instance import  Instances 

def cut_images(shape, new_shape = [640,640]):
    x,y,w,h = 0.5,0.5,1,1
    gt = Instances(np.array([x, y, w, h]),bbox_format= 'xywh')
    r = min(new_shape[0] / shape[0], new_shape[1] / shape[1])
    #r = min(r, 1.0)
    new_unpad = int(round(shape[1] * r)), int(round(shape[0] * r))
    dw, dh = new_shape[1] - new_unpad[0], new_shape[0] - new_unpad[1]  # wh padding
    dw /= 2  # divide padding into 2 sides
    dh /= 2
    ratio = r, r  # width, height ratios
    gt.convert_bbox(format='xyxy')
    gt.denormalize(*shape[:2][::-1])
    gt.scale(*ratio)
    gt.add_padding(dw, dh)
    bbox_after = gt._bboxes.bboxes.reshape(-1).astype(int)
    return bbox_after

# Code

In [3]:
yaml_path = "/home/son/Desktop/Research/ultralytics/ultralytics/cfg/my_config.yaml"
data_info_path = "/home/son/Desktop/Research/ultralytics/ultralytics/cfg/datasets/custom_VOC.yaml"
img_path = "/home/son/Desktop/Research/datasets/VOC/images/val2012/"

In [4]:
data_info = cfg2dict(data_info_path)
cfg = get_cfg(yaml_path)
voc_dataset = build_yolo_dataset(cfg=cfg, batch=1, img_path=img_path,data=data_info)
loader = build_dataloader(cfg=cfg, dataset=voc_dataset, batch=1, workers=cfg.workers)

trainer = DetectionTrainer(yaml_path)
trainer.setup_model()
trainer.set_model_attributes()
# trainer.model.train()
trainer.model.cuda()
trainer.model.train()

train: Scanning /home/son/Desktop/Research/datasets/VOC/labels/val2012.cache... 5823 images, 0 backgrounds, 0 corrupt: 100%|██████████| 5823/5823 [00:00<?, ?it/s]


Ultralytics YOLOv8.0.207 🚀 Python-3.10.13 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 3902MiB)
engine/trainer: task=detect, mode=predict, model=yolov8n.pt, data=ultralytics/cfg/datasets/custom_VOC.yaml, epochs=1, patience=10, batch=1, imgsz=640, save=True, save_period=100, cache=False, device=0, workers=8, project=None, name=predict9, augment=False, exist_ok=False, pretrained=False, optimizer=SGD, verbose=False, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=True, fraction=1.0, cos_lr=False, close_mosaic=10, resume=False, min_memory=False, overlap_mask=True, mask_ratio=4, dropout=0.0, YOLO_VERBOSE=False, val=True, split=val, save_json=False, save_hybrid=False, conf=0.25, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=True, save_conf=False, save_crop=False, hide_labels=True, hide_conf=True, vid_stride=1, line_thickness=3, visualize=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=Tr

DetectionModel(
  (model): Sequential(
    (0): Conv(
      (conv): Conv2d(3, 16, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (bn): BatchNorm2d(16, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
      (act): SiLU(inplace=True)
    )
    (1): Conv(
      (conv): Conv2d(16, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (bn): BatchNorm2d(32, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
      (act): SiLU(inplace=True)
    )
    (2): C2f(
      (cv1): Conv(
        (conv): Conv2d(32, 32, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(32, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (cv2): Conv(
        (conv): Conv2d(48, 32, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(32, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
    

In [7]:
folder_name = "results"
conf = 0.75
ncc_value = 0.6
iter_start = 0
iter_end = 2500


for i, batch in enumerate(loader[0]):
    if (i < iter_start):
        continue
    if (i > iter_end):
        break

    loss_log_image  = []
    path_img        = batch['im_file'][0]
    name_img        = os.path.split(path_img)[-1]

    print(f"[{i}/{len(loader[0])}] Attacking image {name_img} ...")

    batch_tensor    = torch.Tensor(batch['img'].float()).cuda()
    origin_tensor   = torch.Tensor(batch['img'].float()).cuda()
    img_before      = cv2.imread(path_img)
    x,y,_           = img_before.shape              # original img shape
    x_new,y_new     = batch_tensor.shape[-2:]       # shape img after augment with yolov8

    x1,y1,x2,y2     = cut_images((x,y,3),[x_new,y_new])
    
    batch_tensor.requires_grad_()
    batch_tensor.retain_grad()
    b = trainer.model(batch_tensor)
    loss, _ = trainer.model.loss(batch=batch, preds=b)

    loss.retain_grad()
    loss.backward()

    alpha = batch_tensor.grad

    model = YOLO(cfg.get('model'))
    model.conf = conf

    image_to_attack_ori = batch_tensor[:,:,y1:y2,x1:x2].detach().clone().cuda()
    image_to_attack = batch_tensor[:,:,y1:y2,x1:x2].cuda()
    attack_grad     = alpha[:,:,y1:y2,x1:x2].cuda()

    step = 100
    loss_log_image.append(loss)
    folder_result = folder_name +"_"+cfg.get('model')+"_"+ str(ncc_value) +'_ncc_' + str(conf)+"_" + str(iter_start) + "-"+ str(iter_end)
    num_object_min = 0
    num_iter_min   = 0

    for number_of_steps in range(60000):
        res = model.predict(path_img)
        number_object = res[0].boxes.xyxy.shape[0]
        print(number_object)
        print(res[0].boxes.conf)
                
        if number_of_steps == 0:
            save_visualize_image(image_to_attack/255, folder_result ,name_img, 'base')
            path_img           =   f'./img_results/{folder_result}/images_full/val/{name_img[:-4]}_base.jpg'
            step = 0
            num_object_min += number_object
            num_iter_min   += number_of_steps
            save_visualize_image(image_to_attack/255, folder_result ,name_img, f'{number_object}_{number_of_steps}')
            continue
            
        else:
            step = 100
        
        if number_object < num_object_min:
            num_object_min = 0
            num_iter_min   = 0
            num_object_min += number_object
            num_iter_min   += number_of_steps

        
        count = 0
        masks_object_attack                                            = torch.zeros_like(attack_grad)
        for index in range(number_object):
            x1_bbox,y1_bbox,x2_bbox,y2_bbox                            = boxes_to_coor(res[0].boxes.xyxy[index])
            ########################################
            image1 = image_to_attack[:,:,y1_bbox:y2_bbox,x1_bbox:x2_bbox] 
            image2 = image_to_attack_ori[:,:,y1_bbox:y2_bbox,x1_bbox:x2_bbox]
            ncc    = compute_normalized_cross_correlation(image1, image2)
            print(ncc)
            if ncc < ncc_value:
                count += 1
                continue        
            ########################################
            masks_object_attack[:,:,y1_bbox:y2_bbox,x1_bbox:x2_bbox]  += 1
            
        
        masks_object_attack                    = torch.where(masks_object_attack > 0, 1, 0)
        new_image                              = image_to_attack + step*attack_grad*masks_object_attack
        image_to_attack                        = new_image  
        
            
                
        save_visualize_image(new_image/255, folder_result ,name_img, f'{number_object}_{number_of_steps}')
        if count == number_object:
            break
        path_img           =   f'./img_results/{folder_result}/images_full/val/{name_img[:-4]}_{number_object}_{number_of_steps}.jpg'
        
        with torch.no_grad():
            batch_tensor[:,:,y1:y2,x1:x2] = image_to_attack
            
        batch_tensor.requires_grad_()
        batch_tensor.retain_grad()
        b = trainer.model(batch_tensor)

        loss, _ = trainer.model.loss(batch=batch, preds=b)
        

        loss.retain_grad()
        loss.backward()
        alpha = batch_tensor.grad
        image_to_attack = batch_tensor[:,:,y1:y2,x1:x2].cuda()
        attack_grad     = alpha[:,:,y1:y2,x1:x2].cuda()
    
        loss_log_image.append(loss)
        
        torch.cuda.empty_cache()
        gc.collect()
    delete_min_object_iter(folder_result, name_img, num_object_min, num_iter_min)
    save_loss(loss_log_image, folder_result, name_img)

[0/5823] Attacking image 2009_002335.jpg ...



image 1/1 /home/son/Desktop/Research/datasets/VOC/images/val2012/2009_002335.jpg: 640x448 1 motorcycle, 28.8ms
Speed: 1.2ms preprocess, 28.8ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 448)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_002335_base.jpg: 640x448 (no detections), 4.7ms
Speed: 0.9ms preprocess, 4.7ms inference, 0.9ms postprocess per image at shape (1, 3, 640, 448)


1
tensor([0.8373], device='cuda:0')
0
tensor([], device='cuda:0')



image 1/1 /home/son/Desktop/Research/datasets/VOC/images/val2012/2009_000412.jpg: 480x640 3 horses, 5.8ms
Speed: 1.5ms preprocess, 5.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_base.jpg: 480x640 1 horse, 5.4ms
Speed: 1.6ms preprocess, 5.4ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)


[1/5823] Attacking image 2009_000412.jpg ...
3
tensor([0.9163, 0.9023, 0.8969], device='cuda:0')
1
tensor([0.8603], device='cuda:0')
0.9999989093848167



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_1.jpg: 480x640 1 horse, 4.8ms
Speed: 0.9ms preprocess, 4.8ms inference, 1.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_2.jpg: 480x640 1 horse, 4.8ms
Speed: 0.8ms preprocess, 4.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8603], device='cuda:0')
0.9999988749044539
1
tensor([0.8601], device='cuda:0')
0.9999986618594436



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_3.jpg: 480x640 1 horse, 5.5ms
Speed: 1.3ms preprocess, 5.5ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_4.jpg: 480x640 1 horse, 4.8ms
Speed: 0.9ms preprocess, 4.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8620], device='cuda:0')
0.9999977788664256
1
tensor([0.8656], device='cuda:0')
0.9999964877986813



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_5.jpg: 480x640 1 horse, 4.8ms
Speed: 1.1ms preprocess, 4.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_6.jpg: 480x640 1 horse, 4.8ms
Speed: 0.9ms preprocess, 4.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8659], device='cuda:0')
0.9999945373970561
1
tensor([0.8632], device='cuda:0')
0.9999912845227715



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_7.jpg: 480x640 1 horse, 4.8ms
Speed: 1.0ms preprocess, 4.8ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_8.jpg: 480x640 1 horse, 6.1ms
Speed: 2.0ms preprocess, 6.1ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8564], device='cuda:0')
0.999987402874884
1
tensor([0.8579], device='cuda:0')
0.9999826659794662



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_9.jpg: 480x640 1 horse, 4.8ms
Speed: 1.0ms preprocess, 4.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_10.jpg: 480x640 1 horse, 4.8ms
Speed: 0.9ms preprocess, 4.8ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8512], device='cuda:0')
0.9999766636508598
1
tensor([0.8576], device='cuda:0')
0.9999694628602319



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_11.jpg: 480x640 1 horse, 4.8ms
Speed: 0.8ms preprocess, 4.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_12.jpg: 480x640 1 horse, 4.8ms
Speed: 0.9ms preprocess, 4.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8500], device='cuda:0')
0.9999610135177828
1
tensor([0.8511], device='cuda:0')
0.9999514517661819



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_13.jpg: 480x640 1 horse, 4.8ms
Speed: 0.9ms preprocess, 4.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_14.jpg: 480x640 1 horse, 4.8ms
Speed: 0.9ms preprocess, 4.8ms inference, 1.4ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8533], device='cuda:0')
0.9999401665917349
1
tensor([0.8496], device='cuda:0')
0.9999278461769437



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_15.jpg: 480x640 1 horse, 4.9ms
Speed: 0.9ms preprocess, 4.9ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_16.jpg: 480x640 1 horse, 4.9ms
Speed: 0.9ms preprocess, 4.9ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8570], device='cuda:0')
0.9999133981043674
1
tensor([0.8607], device='cuda:0')
0.9998968559376171



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_17.jpg: 480x640 1 horse, 4.8ms
Speed: 0.9ms preprocess, 4.8ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_18.jpg: 480x640 1 horse, 6.2ms
Speed: 1.7ms preprocess, 6.2ms inference, 1.4ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8519], device='cuda:0')
0.9998778840975152
1
tensor([0.8460], device='cuda:0')
0.9998574872520254



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_19.jpg: 480x640 1 horse, 4.8ms
Speed: 0.9ms preprocess, 4.8ms inference, 1.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_20.jpg: 480x640 1 horse, 4.8ms
Speed: 0.8ms preprocess, 4.8ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8531], device='cuda:0')
0.9998363779155971
1
tensor([0.8494], device='cuda:0')
0.999808843392784



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_21.jpg: 480x640 1 horse, 7.9ms
Speed: 2.2ms preprocess, 7.9ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_22.jpg: 480x640 1 horse, 4.8ms
Speed: 0.9ms preprocess, 4.8ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8433], device='cuda:0')
0.9997822763573165
1
tensor([0.8493], device='cuda:0')
0.9997536449664919



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_23.jpg: 480x640 1 horse, 4.8ms
Speed: 0.8ms preprocess, 4.8ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_24.jpg: 480x640 1 horse, 4.8ms
Speed: 0.8ms preprocess, 4.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8439], device='cuda:0')
0.9997252243503565
1
tensor([0.8443], device='cuda:0')
0.9996923152475917



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_25.jpg: 480x640 1 horse, 4.8ms
Speed: 1.0ms preprocess, 4.8ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_26.jpg: 480x640 1 horse, 5.0ms
Speed: 0.9ms preprocess, 5.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8445], device='cuda:0')
0.9996595546548304
1
tensor([0.8387], device='cuda:0')
0.9996200300271387



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_27.jpg: 480x640 1 horse, 4.8ms
Speed: 0.9ms preprocess, 4.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_28.jpg: 480x640 1 horse, 4.8ms
Speed: 0.9ms preprocess, 4.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8476], device='cuda:0')
0.9995799905944284
1
tensor([0.8524], device='cuda:0')
0.9995343335542878



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_29.jpg: 480x640 1 horse, 4.8ms
Speed: 1.0ms preprocess, 4.8ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_30.jpg: 480x640 1 horse, 4.8ms
Speed: 0.9ms preprocess, 4.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8492], device='cuda:0')
0.9994888596977487
1
tensor([0.8542], device='cuda:0')
0.9994444249392415



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_31.jpg: 480x640 1 horse, 4.8ms
Speed: 0.9ms preprocess, 4.8ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_32.jpg: 480x640 1 horse, 4.8ms
Speed: 0.9ms preprocess, 4.8ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8558], device='cuda:0')
0.999393881458771
1
tensor([0.8532], device='cuda:0')
0.9993368712390385



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_33.jpg: 480x640 1 horse, 4.9ms
Speed: 0.9ms preprocess, 4.9ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_34.jpg: 480x640 1 horse, 4.8ms
Speed: 0.9ms preprocess, 4.8ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8529], device='cuda:0')
0.9992860417139762
1
tensor([0.8484], device='cuda:0')
0.9992361021787445



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_35.jpg: 480x640 1 horse, 4.9ms
Speed: 0.8ms preprocess, 4.9ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_36.jpg: 480x640 1 horse, 5.0ms
Speed: 1.0ms preprocess, 5.0ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8489], device='cuda:0')
0.9991659108417572
1
tensor([0.8491], device='cuda:0')
0.9991020119074225



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_37.jpg: 480x640 2 horses, 4.8ms
Speed: 1.2ms preprocess, 4.8ms inference, 1.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_2_38.jpg: 480x640 2 horses, 4.9ms
Speed: 0.9ms preprocess, 4.9ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)


2
tensor([0.8490, 0.7502], device='cuda:0')
0.9990465657656173
0.9997621393724262
2
tensor([0.8467, 0.7607], device='cuda:0')
0.9989775652911024
0.9997472724783172



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_2_39.jpg: 480x640 2 horses, 4.8ms
Speed: 1.1ms preprocess, 4.8ms inference, 1.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_2_40.jpg: 480x640 2 horses, 4.8ms
Speed: 0.9ms preprocess, 4.8ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)


2
tensor([0.8520, 0.7618], device='cuda:0')
0.9989059068492909
0.9997073933522586
2
tensor([0.8494, 0.7641], device='cuda:0')
0.9988164253873819
0.9996634787666863



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_2_41.jpg: 480x640 1 horse, 4.9ms
Speed: 0.9ms preprocess, 4.9ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_42.jpg: 480x640 2 horses, 4.8ms
Speed: 0.9ms preprocess, 4.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8510], device='cuda:0')
0.9987536851672297
2
tensor([0.8481, 0.7838], device='cuda:0')
0.9986732131662389
0.9995887920775575



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_2_43.jpg: 480x640 1 horse, 5.0ms
Speed: 1.3ms preprocess, 5.0ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_44.jpg: 480x640 1 horse, 4.8ms
Speed: 1.0ms preprocess, 4.8ms inference, 1.4ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8478], device='cuda:0')
0.9985701326655384
1
tensor([0.8504], device='cuda:0')
0.9984842212419207



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_45.jpg: 480x640 1 horse, 4.8ms
Speed: 0.8ms preprocess, 4.8ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_46.jpg: 480x640 1 horse, 4.8ms
Speed: 0.8ms preprocess, 4.8ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8424], device='cuda:0')
0.9983779172703426
1
tensor([0.8444], device='cuda:0')
0.9983006344913627



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_47.jpg: 480x640 1 horse, 4.8ms
Speed: 0.9ms preprocess, 4.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_48.jpg: 480x640 1 horse, 4.8ms
Speed: 0.9ms preprocess, 4.8ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8475], device='cuda:0')
0.9982248542282854
1
tensor([0.8482], device='cuda:0')
0.9981261794052432



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_49.jpg: 480x640 1 horse, 4.8ms
Speed: 0.8ms preprocess, 4.8ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_50.jpg: 480x640 1 horse, 4.8ms
Speed: 1.0ms preprocess, 4.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8517], device='cuda:0')
0.9980202335666788
1
tensor([0.8378], device='cuda:0')
0.9978968071276514



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_51.jpg: 480x640 1 horse, 4.9ms
Speed: 0.8ms preprocess, 4.9ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_52.jpg: 480x640 1 horse, 4.8ms
Speed: 0.9ms preprocess, 4.8ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8398], device='cuda:0')
0.9978041153701723
1
tensor([0.8573], device='cuda:0')
0.9976908561393497



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_53.jpg: 480x640 1 horse, 4.8ms
Speed: 0.9ms preprocess, 4.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_54.jpg: 480x640 1 horse, 4.8ms
Speed: 1.2ms preprocess, 4.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8537], device='cuda:0')
0.9975764591837338
1
tensor([0.8591], device='cuda:0')
0.9974611859430971



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_55.jpg: 480x640 1 horse, 4.8ms
Speed: 1.0ms preprocess, 4.8ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_56.jpg: 480x640 1 horse, 5.0ms
Speed: 1.4ms preprocess, 5.0ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8578], device='cuda:0')
0.9973403765666427
1
tensor([0.8686], device='cuda:0')
0.9972164648901098



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_57.jpg: 480x640 1 horse, 4.8ms
Speed: 0.8ms preprocess, 4.8ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_58.jpg: 480x640 1 horse, 4.8ms
Speed: 1.5ms preprocess, 4.8ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8700], device='cuda:0')
0.9970892933981322
1
tensor([0.8772], device='cuda:0')
0.9970613537224547



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_59.jpg: 480x640 1 horse, 4.9ms
Speed: 1.0ms preprocess, 4.9ms inference, 1.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_60.jpg: 480x640 1 horse, 4.8ms
Speed: 0.8ms preprocess, 4.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8754], device='cuda:0')
0.9968958210295396
1
tensor([0.8810], device='cuda:0')
0.9967636133534374



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_61.jpg: 480x640 1 horse, 4.9ms
Speed: 1.1ms preprocess, 4.9ms inference, 1.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_62.jpg: 480x640 1 horse, 4.8ms
Speed: 0.9ms preprocess, 4.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8721], device='cuda:0')
0.9966636825675472
1
tensor([0.8835], device='cuda:0')
0.9964854219712759



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_63.jpg: 480x640 1 horse, 4.9ms
Speed: 0.9ms preprocess, 4.9ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_64.jpg: 480x640 1 horse, 4.8ms
Speed: 1.0ms preprocess, 4.8ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8824], device='cuda:0')
0.9963820800558506
1
tensor([0.8827], device='cuda:0')
0.9962124126269583



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_65.jpg: 480x640 1 horse, 4.8ms
Speed: 1.0ms preprocess, 4.8ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_66.jpg: 480x640 1 horse, 5.4ms
Speed: 1.8ms preprocess, 5.4ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8911], device='cuda:0')
0.9961301365281408
1
tensor([0.8928], device='cuda:0')
0.9959354491764912



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_67.jpg: 480x640 1 horse, 4.8ms
Speed: 1.0ms preprocess, 4.8ms inference, 1.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_68.jpg: 480x640 1 horse, 5.1ms
Speed: 0.8ms preprocess, 5.1ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8912], device='cuda:0')
0.9958258745897574
1
tensor([0.8932], device='cuda:0')
0.9955940303114622



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_69.jpg: 480x640 1 horse, 4.9ms
Speed: 1.0ms preprocess, 4.9ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_70.jpg: 480x640 1 horse, 4.8ms
Speed: 0.9ms preprocess, 4.8ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8911], device='cuda:0')
0.9954311196228036
1
tensor([0.8812], device='cuda:0')
0.9952951832999016



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_71.jpg: 480x640 1 horse, 4.9ms
Speed: 0.8ms preprocess, 4.9ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_72.jpg: 480x640 1 horse, 4.8ms
Speed: 0.8ms preprocess, 4.8ms inference, 1.4ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8881], device='cuda:0')
0.9951271811396147
1
tensor([0.8846], device='cuda:0')
0.9949558269088697



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_73.jpg: 480x640 1 horse, 4.8ms
Speed: 0.8ms preprocess, 4.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_74.jpg: 480x640 1 horse, 4.8ms
Speed: 0.9ms preprocess, 4.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8847], device='cuda:0')
0.9947407581297784
1
tensor([0.8797], device='cuda:0')
0.9946210705455791



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_75.jpg: 480x640 1 horse, 4.8ms
Speed: 1.0ms preprocess, 4.8ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_76.jpg: 480x640 1 horse, 4.8ms
Speed: 1.0ms preprocess, 4.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8752], device='cuda:0')
0.9944843614471922
1
tensor([0.8733], device='cuda:0')
0.9942767481702579



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_77.jpg: 480x640 1 horse, 4.8ms
Speed: 1.1ms preprocess, 4.8ms inference, 1.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_78.jpg: 480x640 1 horse, 6.9ms
Speed: 1.2ms preprocess, 6.9ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8726], device='cuda:0')
0.9940895603237123
1
tensor([0.8716], device='cuda:0')
0.9938991807237884



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_79.jpg: 480x640 1 horse, 4.8ms
Speed: 1.0ms preprocess, 4.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_80.jpg: 480x640 1 horse, 4.8ms
Speed: 0.8ms preprocess, 4.8ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8693], device='cuda:0')
0.9936134374634887
1
tensor([0.8604], device='cuda:0')
0.9934512411503571



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_81.jpg: 480x640 1 horse, 5.9ms
Speed: 1.1ms preprocess, 5.9ms inference, 1.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_82.jpg: 480x640 1 horse, 4.8ms
Speed: 0.9ms preprocess, 4.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8519], device='cuda:0')
0.9931968586693299
1
tensor([0.8428], device='cuda:0')
0.9930163007361048



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_83.jpg: 480x640 1 horse, 4.8ms
Speed: 0.9ms preprocess, 4.8ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_84.jpg: 480x640 1 horse, 4.8ms
Speed: 0.9ms preprocess, 4.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8550], device='cuda:0')
0.9928549021907797
1
tensor([0.8559], device='cuda:0')
0.9925669757507497



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_85.jpg: 480x640 1 horse, 4.8ms
Speed: 1.0ms preprocess, 4.8ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_86.jpg: 480x640 1 horse, 4.8ms
Speed: 0.9ms preprocess, 4.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8658], device='cuda:0')
0.992428585827133
1
tensor([0.8641], device='cuda:0')
0.9921584783154763



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_87.jpg: 480x640 1 horse, 4.8ms
Speed: 1.0ms preprocess, 4.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_88.jpg: 480x640 1 horse, 5.0ms
Speed: 0.9ms preprocess, 5.0ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8473], device='cuda:0')
0.9919059608812679
1
tensor([0.8583], device='cuda:0')
0.9916787605517609



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_89.jpg: 480x640 1 horse, 4.9ms
Speed: 1.0ms preprocess, 4.9ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_90.jpg: 480x640 1 horse, 4.9ms
Speed: 0.9ms preprocess, 4.9ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8541], device='cuda:0')
0.9913795408714511
1
tensor([0.8694], device='cuda:0')
0.9913697657122935



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_91.jpg: 480x640 1 horse, 4.8ms
Speed: 1.0ms preprocess, 4.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_92.jpg: 480x640 1 horse, 4.9ms
Speed: 0.9ms preprocess, 4.9ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8700], device='cuda:0')
0.9910443009565432
1
tensor([0.8661], device='cuda:0')
0.9908051437934958



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_93.jpg: 480x640 1 horse, 4.8ms
Speed: 1.0ms preprocess, 4.8ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_94.jpg: 480x640 1 horse, 4.9ms
Speed: 1.1ms preprocess, 4.9ms inference, 1.4ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8397], device='cuda:0')
0.9905035385124641
1
tensor([0.8247], device='cuda:0')
0.990231689645021



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_95.jpg: 480x640 1 horse, 5.0ms
Speed: 0.9ms preprocess, 5.0ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_96.jpg: 480x640 1 horse, 4.8ms
Speed: 0.9ms preprocess, 4.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8357], device='cuda:0')
0.9901852676803633
1
tensor([0.8416], device='cuda:0')
0.9899011692106713



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_97.jpg: 480x640 1 horse, 4.8ms
Speed: 0.8ms preprocess, 4.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_98.jpg: 480x640 1 horse, 4.8ms
Speed: 0.8ms preprocess, 4.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8265], device='cuda:0')
0.9893714641561256
1
tensor([0.8046], device='cuda:0')
0.9891197327474104



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_99.jpg: 480x640 1 horse, 4.8ms
Speed: 0.8ms preprocess, 4.8ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8307], device='cuda:0')
0.9889293143343505



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_100.jpg: 480x640 1 horse, 5.0ms
Speed: 0.9ms preprocess, 5.0ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_101.jpg: 480x640 1 horse, 4.8ms
Speed: 1.2ms preprocess, 4.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8248], device='cuda:0')
0.988747110464856
1
tensor([0.8299], device='cuda:0')
0.988383337089173



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_102.jpg: 480x640 1 horse, 4.9ms
Speed: 0.9ms preprocess, 4.9ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_103.jpg: 480x640 1 horse, 4.8ms
Speed: 0.9ms preprocess, 4.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8271], device='cuda:0')
0.9881081551605551
1
tensor([0.8246], device='cuda:0')
0.987754209294997



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_104.jpg: 480x640 1 horse, 4.8ms
Speed: 0.9ms preprocess, 4.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_105.jpg: 480x640 1 horse, 4.8ms
Speed: 1.0ms preprocess, 4.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8048], device='cuda:0')
0.9875550822823219
1
tensor([0.8141], device='cuda:0')
0.9873497363336037



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_106.jpg: 480x640 1 horse, 4.9ms
Speed: 1.1ms preprocess, 4.9ms inference, 1.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_107.jpg: 480x640 1 horse, 4.8ms
Speed: 1.0ms preprocess, 4.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.7922], device='cuda:0')
0.9872127160369293
1
tensor([0.7912], device='cuda:0')
0.9867722764098534



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_108.jpg: 480x640 1 horse, 4.9ms
Speed: 0.9ms preprocess, 4.9ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_109.jpg: 480x640 1 horse, 6.0ms
Speed: 2.7ms preprocess, 6.0ms inference, 1.7ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8396], device='cuda:0')
0.9867825998272183
1
tensor([0.8268], device='cuda:0')
0.9864726779846961



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_110.jpg: 480x640 1 horse, 4.8ms
Speed: 1.0ms preprocess, 4.8ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_111.jpg: 480x640 1 horse, 4.8ms
Speed: 1.0ms preprocess, 4.8ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8439], device='cuda:0')
0.9861956237269525
1
tensor([0.8221], device='cuda:0')
0.9859642452129851



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_112.jpg: 480x640 1 horse, 4.8ms
Speed: 0.9ms preprocess, 4.8ms inference, 1.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_113.jpg: 480x640 1 horse, 4.8ms
Speed: 0.9ms preprocess, 4.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.8210], device='cuda:0')
0.985575892582855
1
tensor([0.8130], device='cuda:0')
0.9853793530202195



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_114.jpg: 480x640 1 horse, 4.9ms
Speed: 1.1ms preprocess, 4.9ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2009_000412_1_115.jpg: 480x640 (no detections), 4.8ms
Speed: 0.9ms preprocess, 4.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)


1
tensor([0.7676], device='cuda:0')
0.9848171501303616
0
tensor([], device='cuda:0')
[2/5823] Attacking image 2008_002410.jpg ...



image 1/1 /home/son/Desktop/Research/datasets/VOC/images/val2012/2008_002410.jpg: 640x576 2 cats, 32.8ms
Speed: 1.8ms preprocess, 32.8ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 576)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_base.jpg: 640x576 2 cats, 5.8ms
Speed: 1.1ms preprocess, 5.8ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 576)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_2_1.jpg: 640x576 2 cats, 5.6ms


2
tensor([0.9178, 0.8894], device='cuda:0')
2
tensor([0.9116, 0.8981], device='cuda:0')
0.9999989482165816
0.9999991387941028


Speed: 1.4ms preprocess, 5.6ms inference, 1.4ms postprocess per image at shape (1, 3, 640, 576)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_2_2.jpg: 640x576 2 cats, 5.6ms
Speed: 1.4ms preprocess, 5.6ms inference, 1.5ms postprocess per image at shape (1, 3, 640, 576)


2
tensor([0.9116, 0.8981], device='cuda:0')
0.9999988808983629
0.9999989912818968
2
tensor([0.9115, 0.8982], device='cuda:0')
0.9999975083260642
0.9999986746060721



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_2_3.jpg: 640x576 2 cats, 6.6ms
Speed: 1.0ms preprocess, 6.6ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 576)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_2_4.jpg: 640x576 2 cats, 5.5ms
Speed: 1.1ms preprocess, 5.5ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 576)


2
tensor([0.9119, 0.8981], device='cuda:0')
0.9999942703113661
0.9999977813569509
2
tensor([0.9122, 0.9003], device='cuda:0')



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_2_5.jpg: 640x576 2 cats, 5.5ms
Speed: 1.1ms preprocess, 5.5ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 576)


0.9999886591445357
0.9999955939124568
2
tensor([0.9112, 0.9004], device='cuda:0')
0.9999802393705362
0.9999905410846113



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_2_6.jpg: 640x576 2 cats, 5.5ms
Speed: 1.0ms preprocess, 5.5ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 576)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_2_7.jpg: 640x576 2 cats, 5.6ms
Speed: 0.9ms preprocess, 5.6ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 576)


2
tensor([0.9118, 0.8969], device='cuda:0')
0.9999689002143382
0.9999807221148255
2
tensor([0.9117, 0.8997], device='cuda:0')
0.9999538344216783
0.9999639391205211



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_2_8.jpg: 640x576 2 cats, 5.6ms
Speed: 1.2ms preprocess, 5.6ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 576)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_2_9.jpg: 640x576 2 cats, 5.5ms
Speed: 1.1ms preprocess, 5.5ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 576)


2
tensor([0.9106, 0.8956], device='cuda:0')
0.9999349836232366
0.9999401334616932
2
tensor([0.9091, 0.8980], device='cuda:0')
0.9999116175219426
0.9999088722480117



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_2_10.jpg: 640x576 2 cats, 5.7ms
Speed: 1.0ms preprocess, 5.7ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 576)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_2_11.jpg: 640x576 2 cats, 5.5ms
Speed: 1.1ms preprocess, 5.5ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 576)


2
tensor([0.9081, 0.8984], device='cuda:0')
0.9998832470156414
0.9998679861206579
2
tensor([0.9110, 0.8977], device='cuda:0')
0.9998474326701379
0.9998167406917908



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_2_12.jpg: 640x576 2 cats, 5.5ms
Speed: 1.1ms preprocess, 5.5ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 576)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_2_13.jpg: 640x576 2 cats, 5.5ms
Speed: 1.1ms preprocess, 5.5ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 576)


2
tensor([0.9093, 0.8935], device='cuda:0')
0.9998041461647029
0.9997541517147489
2
tensor([0.9106, 0.8881], device='cuda:0')
0.9997533442465796
0.9996793622913334



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_2_14.jpg: 640x576 2 cats, 5.6ms
Speed: 1.7ms preprocess, 5.6ms inference, 1.4ms postprocess per image at shape (1, 3, 640, 576)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_2_15.jpg: 640x576 2 cats, 5.7ms
Speed: 1.0ms preprocess, 5.7ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 576)


2
tensor([0.9070, 0.8775], device='cuda:0')
0.9996946405244662
0.9995926486371525
2
tensor([0.9079, 0.8763], device='cuda:0')
0.9996281927711929
0.999490248014616



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_2_16.jpg: 640x576 2 cats, 5.6ms
Speed: 1.1ms preprocess, 5.6ms inference, 1.7ms postprocess per image at shape (1, 3, 640, 576)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_2_17.jpg: 640x576 2 cats, 5.5ms
Speed: 1.2ms preprocess, 5.5ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 576)


2
tensor([0.9053, 0.8692], device='cuda:0')
0.999553824769487
0.9993795245309314
2
tensor([0.9051, 0.8625], device='cuda:0')
0.9994709829986589
0.9992499264442922



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_2_18.jpg: 640x576 2 cats, 5.6ms
Speed: 1.3ms preprocess, 5.6ms inference, 1.4ms postprocess per image at shape (1, 3, 640, 576)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_2_19.jpg: 640x576 2 cats, 5.5ms
Speed: 1.3ms preprocess, 5.5ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 576)


2
tensor([0.9017, 0.8573], device='cuda:0')
0.9993801546413348
0.9990992926460573
2
tensor([0.9054, 0.8562], device='cuda:0')
0.9992811180300174
0.9989369312398619



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_2_20.jpg: 640x576 2 cats, 5.5ms
Speed: 1.2ms preprocess, 5.5ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 576)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_2_21.jpg: 640x576 2 cats, 5.5ms
Speed: 1.0ms preprocess, 5.5ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 576)


2
tensor([0.9055, 0.8521], device='cuda:0')
0.999173780378813
0.9987575438603167
2
tensor([0.9007, 0.8432], device='cuda:0')
0.9990571473350381
0.9985611215473299



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_2_22.jpg: 640x576 2 cats, 5.6ms
Speed: 1.2ms preprocess, 5.6ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 576)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_2_23.jpg: 640x576 2 cats, 5.5ms
Speed: 1.0ms preprocess, 5.5ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 576)


2
tensor([0.9018, 0.8444], device='cuda:0')
0.9989326370198771
0.998347580120999
2
tensor([0.9001, 0.8378], device='cuda:0')
0.9987987040702953
0.9981166743615728



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_2_24.jpg: 640x576 2 cats, 5.6ms
Speed: 1.1ms preprocess, 5.6ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 576)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_2_25.jpg: 640x576 2 cats, 5.5ms
Speed: 1.0ms preprocess, 5.5ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 576)


2
tensor([0.9035, 0.8308], device='cuda:0')
0.9986559329392636
0.9978681431498757
2
tensor([0.9018, 0.8074], device='cuda:0')
0.9985039425257902
0.9975953981689352



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_2_26.jpg: 640x576 2 cats, 5.5ms
Speed: 1.3ms preprocess, 5.5ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 576)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_2_27.jpg: 640x576 1 cat, 5.5ms
Speed: 1.0ms preprocess, 5.5ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 576)


2
tensor([0.9051, 0.8010], device='cuda:0')
0.9983426446702014
0.9973236520229379
1
tensor([0.8999], device='cuda:0')
0.9981720957778109



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_1_28.jpg: 640x576 1 cat, 5.5ms
Speed: 1.0ms preprocess, 5.5ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 576)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_1_29.jpg: 640x576 1 cat, 5.6ms
Speed: 1.1ms preprocess, 5.6ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 576)


1
tensor([0.8988], device='cuda:0')
0.9979920853842802
1
tensor([0.8980], device='cuda:0')
0.9978029970822527



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_1_30.jpg: 640x576 1 cat, 6.1ms
Speed: 1.1ms preprocess, 6.1ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 576)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_1_31.jpg: 640x576 1 cat, 5.5ms
Speed: 1.2ms preprocess, 5.5ms inference, 1.5ms postprocess per image at shape (1, 3, 640, 576)


1
tensor([0.8997], device='cuda:0')
0.9976042772947877
1
tensor([0.8985], device='cuda:0')
0.997396704114699



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_1_32.jpg: 640x576 1 cat, 5.5ms
Speed: 1.0ms preprocess, 5.5ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 576)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_1_33.jpg: 640x576 1 cat, 5.5ms
Speed: 1.1ms preprocess, 5.5ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 576)


1
tensor([0.9007], device='cuda:0')
0.9971780110463939
1
tensor([0.8957], device='cuda:0')
0.9969516239668291



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_1_34.jpg: 640x576 1 cat, 5.6ms
Speed: 1.1ms preprocess, 5.6ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 576)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_1_35.jpg: 640x576 1 cat, 7.4ms
Speed: 1.1ms preprocess, 7.4ms inference, 2.8ms postprocess per image at shape (1, 3, 640, 576)


1
tensor([0.8982], device='cuda:0')
0.9967142319529334
1
tensor([0.8967], device='cuda:0')
0.9964666405345621



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_1_36.jpg: 640x576 1 cat, 5.6ms
Speed: 1.4ms preprocess, 5.6ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 576)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_1_37.jpg: 640x576 1 cat, 5.5ms
Speed: 1.1ms preprocess, 5.5ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 576)


1
tensor([0.8946], device='cuda:0')
0.9962097731343265
1
tensor([0.8962], device='cuda:0')
0.9959429890741568



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_1_38.jpg: 640x576 1 cat, 5.8ms
Speed: 1.0ms preprocess, 5.8ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 576)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_1_39.jpg: 640x576 1 cat, 5.5ms
Speed: 1.1ms preprocess, 5.5ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 576)


1
tensor([0.9005], device='cuda:0')
0.9956661431678923
1
tensor([0.8975], device='cuda:0')
0.995379500795148



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_1_40.jpg: 640x576 1 cat, 5.5ms
Speed: 1.2ms preprocess, 5.5ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 576)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_1_41.jpg: 640x576 1 cat, 5.6ms
Speed: 1.2ms preprocess, 5.6ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 576)


1
tensor([0.8964], device='cuda:0')
0.9950829375656624
1
tensor([0.8920], device='cuda:0')
0.9947766239274461



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_1_42.jpg: 640x576 1 cat, 5.5ms
Speed: 1.0ms preprocess, 5.5ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 576)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_1_43.jpg: 640x576 1 cat, 5.6ms
Speed: 1.3ms preprocess, 5.6ms inference, 1.4ms postprocess per image at shape (1, 3, 640, 576)


1
tensor([0.8920], device='cuda:0')
0.9944611779552651
1
tensor([0.8895], device='cuda:0')
0.9941358170831373



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_1_44.jpg: 640x576 1 cat, 5.5ms
Speed: 1.3ms preprocess, 5.5ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 576)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_1_45.jpg: 640x576 1 cat, 5.5ms
Speed: 1.1ms preprocess, 5.5ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 576)


1
tensor([0.8843], device='cuda:0')
0.9938192688181968
1
tensor([0.8890], device='cuda:0')
0.9934591454480721



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_1_46.jpg: 640x576 1 cat, 5.7ms
Speed: 1.6ms preprocess, 5.7ms inference, 1.5ms postprocess per image at shape (1, 3, 640, 576)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_1_47.jpg: 640x576 1 cat, 5.6ms
Speed: 1.3ms preprocess, 5.6ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 576)


1
tensor([0.8807], device='cuda:0')
0.9931241842386426
1
tensor([0.8690], device='cuda:0')
0.9927417085284141



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_1_48.jpg: 640x576 1 cat, 5.6ms
Speed: 1.3ms preprocess, 5.6ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 576)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_1_49.jpg: 640x576 1 cat, 5.5ms
Speed: 1.1ms preprocess, 5.5ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 576)


1
tensor([0.8805], device='cuda:0')
0.9923676739277196
1
tensor([0.8726], device='cuda:0')
0.9920310121302106



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_1_50.jpg: 640x576 1 cat, 5.6ms
Speed: 1.4ms preprocess, 5.6ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 576)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_1_51.jpg: 640x576 1 cat, 5.5ms
Speed: 1.1ms preprocess, 5.5ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 576)


1
tensor([0.8775], device='cuda:0')
0.9916622469924429
1
tensor([0.8783], device='cuda:0')
0.9912378842678927



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_1_52.jpg: 640x576 1 cat, 5.5ms
Speed: 1.0ms preprocess, 5.5ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 576)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_1_53.jpg: 640x576 1 cat, 5.5ms
Speed: 1.1ms preprocess, 5.5ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 576)


1
tensor([0.8783], device='cuda:0')
0.9908484836453945
1
tensor([0.8651], device='cuda:0')
0.9903561935682297



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_1_54.jpg: 640x576 1 cat, 5.5ms
Speed: 1.0ms preprocess, 5.5ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 576)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_1_55.jpg: 640x576 1 cat, 5.6ms
Speed: 1.0ms preprocess, 5.6ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 576)


1
tensor([0.8633], device='cuda:0')
0.9899942574559812
1
tensor([0.8729], device='cuda:0')
0.9895523284939092



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_1_56.jpg: 640x576 1 cat, 5.5ms
Speed: 1.4ms preprocess, 5.5ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 576)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_1_57.jpg: 640x576 1 cat, 5.5ms
Speed: 1.1ms preprocess, 5.5ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 576)


1
tensor([0.8723], device='cuda:0')
0.9890281801449436
1
tensor([0.8764], device='cuda:0')
0.9885634228275378



image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_1_58.jpg: 640x576 1 cat, 5.5ms
Speed: 1.0ms preprocess, 5.5ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 576)

image 1/1 /home/son/Desktop/Research/ultralytics/img_results/results_yolov8n.pt_0.6_ncc_0.75_0-2500/images_full/val/2008_002410_1_59.jpg: 640x576 1 cat, 5.6ms
Speed: 1.1ms preprocess, 5.6ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 576)


1
tensor([0.8912], device='cuda:0')
0.9880888714565975
1
tensor([0.8576], device='cuda:0')
0.9876047768442986


KeyboardInterrupt: 

# Convert PASCAL VOC label to YOLO

In [2]:
import xml.etree.ElementTree as ET

from tqdm import tqdm
from pathlib import Path
import shutil

names_dict = {
  0: "aeroplane",
  1: "bicycle",
  2: "bird",
  3: "boat",
  4: "bottle",
  5: "bus",
  6: "car",
  7: "cat",
  8: "chair",
  9: "cow",
  10: "diningtable",
  11: "dog",
  12: "horse",
  13: "motorbike",
  14: "person",
  15: "pottedplant",
  16: "sheep",
  17: "sofa",
  18: "train",
  19: "tvmonitor",
}

def convert_label(path, lb_path, year, image_id):
    def convert_box(size, box):
        dw, dh = 1. / size[0], 1. / size[1]
        x, y, w, h = (box[0] + box[1]) / 2.0 - 1, (box[2] + box[3]) / 2.0 - 1, box[1] - box[0], box[3] - box[2]
        return x * dw, y * dh, w * dw, h * dh

    in_file = open(path / f'VOC{year}/Annotations/{image_id}.xml')
    out_file = open(lb_path, 'w')
    tree = ET.parse(in_file)
    root = tree.getroot()
    size = root.find('size')
    w = int(size.find('width').text)
    h = int(size.find('height').text)

    names = list(names_dict.values())  # names list
    for obj in root.iter('object'):
        cls = obj.find('name').text
        if cls in names and int(obj.find('difficult').text) != 1:
            xmlbox = obj.find('bndbox')
            bb = convert_box((w, h), [float(xmlbox.find(x).text) for x in ('xmin', 'xmax', 'ymin', 'ymax')])
            cls_id = names.index(cls)  # class id
            out_file.write(" ".join(str(a) for a in (cls_id, *bb)) + '\n')


# # Download
# dir = Path(yaml['path'])  # dataset root dir
# url = 'https://github.com/ultralytics/yolov5/releases/download/v1.0/'
# urls = [f'{url}VOCtrainval_06-Nov-2007.zip',  # 446MB, 5012 images
#         f'{url}VOCtest_06-Nov-2007.zip',  # 438MB, 4953 images
#         f'{url}VOCtrainval_11-May-2012.zip']  # 1.95GB, 17126 images
# download(urls, dir=dir / 'images', curl=True, threads=3)

dir = Path("../datasets/VOC")

# Convert
path = dir / 'images/VOCdevkit'
for year, image_set in ('2012', 'train'), ('2012', 'val'):
    imgs_path = dir / 'images' / f'{image_set}{year}'
    lbs_path = dir / 'labels' / f'{image_set}{year}'
    imgs_path.mkdir(exist_ok=True, parents=True)
    lbs_path.mkdir(exist_ok=True, parents=True)

    with open(path / f'VOC{year}/ImageSets/Main/{image_set}.txt') as f:
        image_ids = f.read().strip().split()
    # print(len(image_ids))
    for id in tqdm(image_ids, desc=f'{image_set}{year}'):
        f = path / f'VOC{year}/JPEGImages/{id}.jpg'  # old img path
        lb_path = (lbs_path / f.name).with_suffix('.txt')  # new label path
        shutil.move(f, imgs_path / f.name)
        # f.rename(imgs_path / f.name)  # move image
        convert_label(path, lb_path, year, id)  # convert labels to YOLO format

val2012: 100%|██████████| 5823/5823 [00:00<00:00, 6979.88it/s]
